### ISSUE TITLE
Can't get Sample tweak to fire

### ISSUE THREAD

**Issue by sddevstudio** [angelXwind/simject#11]
Hi Karen,

I can't seem to get your sample tweak to fire. Below are the steps I have taken.

macOS Sierra: 10.12.2
Xcode: Version 8.2.1 (8C1002)
Simulator: Version 10.0 (SimulatorApp-726.7

1. I have compiled simject, without any errors.
2. Launched simulator running iPhone6s
3. Ran the command-line respring_simulator tool and it resprings.
4. Compile the sample and copy the dylib and plist into /opt/simject/
5. Run respring_simulator
6. Wait for alert message box to appear when the springboard launches
7. :( it never shows up
8. Checked Console didn't notice any obvious errors related to this. 

Is there something in the logs I can look for to see what might be causing some issues?

Thanks in advance,
Stephen

**Comment by Packetfahrer** [comment]
try this works for me 
https://github.com/PoomSmart/simject

**Comment by sddevstudio** [comment]
thanks @Packetfahrer i just gave this a try and am still getting the same results.

**Comment by angelXwind** [comment]
@sddevstudio Are you using the latest Theos? If not, you must fakesign your dylibs manually.

First, make sure you have `ldid` installed. If you do not, `brew install ldid`.

Secondly, paste this into a Terminal: `for dylib in /opt/simject/*.dylib; do ldid -S "$dylib"; done`. This will use `ldid` to fakesign all dylibs loading into simject.

**Comment by sddevstudio** [comment]
awesome thank you very much! It was the manual fakesigning.
