### ISSUE TITLE
`make setup` fails with a "No such file or directory" error

### ISSUE THREAD

**Issue by TimXcode** [angelXwind/simject#16]
Trying to run make setup on Sierra 10.12.5 gives 
````
Makefile:6: /makefiles/common.mk: No such file or directory
Makefile:12: /tool.mk: No such file or directory
make[1]: *** No rule to make target `/tool.mk'.  Stop.
make: *** [clean] Error 2`
```
Please help

**Comment by angelXwind** [comment]
You didn't set up Theos correctly (you're missing the `$THEOS` environment variable).

Refer to https://github.com/theos/theos/wiki/Installation for more information.
