### ISSUE TITLE
Does not see iOS 11 Simulator

### ISSUE THREAD

**Issue by andrewwiik** [angelXwind/simject#21]
It just doesn't :(

**Comment by PoomSmart** [comment]
#22 This pull request uses more reliable way to inject dylibs and it should now see any simulator truly available. You can try.

**Comment by andrewwiik** [comment]
Still having issues, I have the beta XCode and stable installed, but I used xcode-select to select the beta one yet it still can't see them :(

**Comment by andrewwiik** [comment]
`Injecting appropriate dynamic libraries from /opt/simject...
Respringing 6E80CF2C-C1E3-4932-BEDD-6DE39D2B0523 (iPhone 7) ...
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
The operation couldn’t be completed. No such file or directory
No such file or directory
Respringing 98DF8D53-E751-4CEF-8683-CF9A02BDA6B8 (iPhone 7) ...
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
The operation couldn’t be completed. No such file or directory
No such file or directory`

**Comment by PoomSmart** [comment]
@andrewwiik I presume it is by the absence of `launchctl` in iOS 11+ SDK, causing an error that file is not found. One could copy the aforementioned binary from earlier SDK (iOS 10 is recommended) to `/bin` of the SDK root.

**Comment by andrewwiik** [comment]
isn't this something that simject should somehow handle though? @PoomSmart

**Comment by PoomSmart** [comment]
@andrewwiik It was something I overlooked. There are two ways: (1) Auto-detect iOS 10.x SDK and copy the binary on-the-fly if necessary. (2) Just warn the user that the binary is not there and it must exist in iOS 11 SDK in order to make simject work.

**Comment by PoomSmart** [comment]
@andrewwiik Please confirm if the solution works for you so maybe this issue can be finally closed. @angelXwind

**Comment by andrewwiik** [comment]
@PoomSmart I wouldn't be able to consider this issue closed until one of those solutions is actually implemented in the code and a pull request is made, but I will test and get back to you give me a few mins

**Comment by andrewwiik** [comment]
@PoomSmart maybe I am putting it in the wrong place but I am still getting the error

**Comment by PoomSmart** [comment]
@andrewwiik Could you check if in `~/Library/Developer/CoreSimulator/Devices` contains any folder named UDID of any simulator as indicated in your simject output?

**Comment by andrewwiik** [comment]
@PoomSmart A folder for the UDID of the simulator that simject outputs is indeed present

**Comment by andrewwiik** [comment]
@PoomSmart Simject seems the simulator now, that is fixed, but simject is not working on the XCode beta simulators for actual respringing and injecting

**Comment by PoomSmart** [comment]
@andrewwiik What kind of error you face on Xcode beta at this point, the same one?

**Comment by andrewwiik** [comment]
@PoomSmart If I run the command manually this is the output:

`xcrun simctl spawn 98DF8D53-E751-4CEF-8683-CF9A02BDA6B8 launchctl setenv DYLD_INSERT_LIBRARIES /opt/simject/simject.dylib
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
The operation couldn’t be completed. No such file or directory
No such file or directory`

**Comment by PoomSmart** [comment]
@andrewwiik Please check if `launchctl` is actually inside `/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/bin`.

**Comment by andrewwiik** [comment]
@PoomSmart OHHHH, you said put it in the SDK above, not the runtime root, these are two different folders haha give me one sec

**Comment by andrewwiik** [comment]
@PoomSmart worked

**Comment by andrewwiik** [comment]
I'll close this issue but let's see if we can get a command to copy that file put in the GroupMe @angelXwind @PoomSmart
