### ISSUE TITLE
Respring_Simulator Freezes Simulator - xcode 9 beta 5

### ISSUE THREAD

**Issue by LaughingQuoll** [angelXwind/simject#28]
When using iOS 11 simulator on xcode beta 5 the respring command makes the simulator freeze.

**Comment by PoomSmart** [comment]
Make sure you have `CydiaSubstrate.framework` placed at the correct location. Check the updated README for copying the framework in case of iOS 11 runtime (that comes with Xcode app). @LaughingQuoll

**Comment by LaughingQuoll** [comment]
Tried the above.

Reinstalled MacOS, solved it.
