### ISSUE TITLE
Making Setup with XCode 9 GM

### ISSUE THREAD

**Issue by LaughingQuoll** [angelXwind/simject#29]
Doing so provides this error:

clang: error: invalid iOS deployment version '-mios-simulator-version-min=11.0', iOS 10 is the maximum deployment target for 32-bit targets [-Winvalid-ios-deployment-target]

I had to set it up with xcode 8 for it to go through.

**Comment by da1996** [comment]
delete i386 from all makefile in simject folder and it work ;)

**Comment by LaughingQuoll** [comment]
@da1996 for new users this might not be as apparent. I'm merely pointing out that the removal of 32bit on xcode 9 will cause this issue for new and inexperienced users.

**Comment by angelXwind** [comment]
Closing as I just fixed this issue in the latest commit as of this writing (`fe29d46fbf33b40d1a51ce9d46cf37765bbf5e5b`).
