### ISSUE TITLE
Required code signature missing for '/opt/simject/simject.dylib'

### ISSUE THREAD

**Issue by deepfriedfilth** [angelXwind/simject#30]
When using **respring_simulator** bin, simulator does respring, but I am also getting this output, and any dylibs in /opt/simject are not being included:

```
dyld: warning: could not load inserted library '/opt/simject/simject.dylib' because no suitable image found.  Did find:
        /opt/simject/simject.dylib: required code signature missing for '/opt/simject/simject.dylib'
```

I should also note that I am hoping to use simject to throw myself into a tweak development process.. (My experience is mostly front-end web dev thus far). I am yet to start a project using either iOSOpenDev or strictly theos. Right now, I am just `dpkg-deb`-ing some of my favorite tweaks to test injecting into the simulator.

**Comment by deepfriedfilth** [comment]
Just noticed this in a closed issue (https://github.com/angelXwind/simject/issues/11#issuecomment-271221510) and tried to force fakesign, although I am running the latest version of **theos**. Getting same warning message upon respringing the sim.

Probably irrelevant, but ya never know..

**Comment by PoomSmart** [comment]
Provided that you have successfully installed ldid, you need not to manually fakesign the dylibs again once compiled. Just let theos handle everything for you.
