### ISSUE TITLE
invalid iOS development version

### ISSUE THREAD

**Issue by pbr0ck3r** [angelXwind/simject#33]
This could be a theos issue (sucuessfulling installed theos). But I was install simject on a new laptop and got the following error when running `make setup`

> Making all for tool respring_simulator…
make[3]: Nothing to be done for 'internal-tool-compile'.
Copying binaries...
> Making all for tweak simject…
==> Preprocessing simject.xm…
==> Compiling simject.xm (i386)…
clang: error: invalid iOS deployment version '-mios-simulator-version-min=11.2', iOS 10 is the maximum deployment target for 32-bit targets [-Winvalid-ios-deployment-target]
make[4]: *** [/Users/USERNAME/simject/simject/.theos/obj/iphone_simulator/i386/simject.xm.b3a58ea8.o] Error 1
make[3]: *** [/Users/USERNAME/simject/simject/.theos/obj/iphone_simulator/i386/simject.dylib] Error 2
make[2]: *** [internal-library-all_] Error 2
make[1]: *** [simject.all.tweak.variables] Error 2
make: *** [all] Error 2

I am trying to get simject working with iOS 11.

**Comment by PoomSmart** [comment]
simject tweak is meant to be compiled in 64-bit only if you target iOS 11. By default, this line should have addressed your issue (https://github.com/angelXwind/simject/blob/master/simject/Makefile#L1) by targeting iOS 5.0. So in this case, you may want to remove i386 from the ARCH flags of the global Makefile manually.

**Comment by pbr0ck3r** [comment]
Removing `i386` from the `simject/MakeFile` worked
