### ISSUE TITLE
Can't make setup

### ISSUE THREAD

**Issue by jacc** [angelXwind/simject#34]
```
Makefile:3: /makefiles/common.mk: No such file or directory
Makefile:9: /tool.mk: No such file or directory
make[1]: *** No rule to make target `/tool.mk'.  Stop.
make: *** [clean] Error 2
```

not really sure what to do here lol

**Comment by jacc** [comment]
I...lied? I just retried and now it suddenly works lmao

**Comment by MindfulMe** [comment]
I have the same problem, but I can't resolve it ...
mapincs-Mac:simject mapinc$ make setup
==> Cleaning…
xcrun: error: SDK "iphonesimulator" cannot be located
==> Cleaning…
mkdir: /opt/simject/respring_simulator/.theos: Permission denied
make[1]: *** [/opt/simject/respring_simulator/.theos/build_session] Error 1
make: *** [all] Error 2
mapincs-Mac:simject mapinc$ sudo make setup
Password:
Makefile:3: /makefiles/common.mk: No such file or directory
Makefile:9: /tool.mk: No such file or directory
make[1]: *** No rule to make target `/tool.mk'.  Stop.
make: *** [clean] Error 2
mapincs-Mac:simject mapinc$ sudo make setup
Makefile:3: /makefiles/common.mk: No such file or directory
Makefile:9: /tool.mk: No such file or directory
make[1]: *** No rule to make target `/tool.mk'.  Stop.
make: *** [clean] Error 2
