### ISSUE TITLE
Can't "make setup"

### ISSUE THREAD

**Issue by MindfulMe** [angelXwind/simject#36]
Here is the log:

mapincs-Mac:simject mapinc$ make setup
==> Cleaning…
xcrun: error: SDK "iphonesimulator" cannot be located
==> Cleaning…
mkdir: /opt/simject/respring_simulator/.theos: Permission denied
make[1]: *** [/opt/simject/respring_simulator/.theos/build_session] Error 1
make: *** [all] Error 2
mapincs-Mac:simject mapinc$ sudo make setup
Password:
Makefile:3: /makefiles/common.mk: No such file or directory
Makefile:9: /tool.mk: No such file or directory
make[1]: *** No rule to make target `/tool.mk'.  Stop.
make: *** [clean] Error 2
mapincs-Mac:simject mapinc$ sudo make setup
Makefile:3: /makefiles/common.mk: No such file or directory
Makefile:9: /tool.mk: No such file or directory
make[1]: *** No rule to make target `/tool.mk'.  Stop.
make: *** [clean] Error 2

**Comment by MindfulMe** [comment]
Sorry, looks like my THEOS env variable does not work correctly (missing the $THEOS environment variable).
https://github.com/theos/theos/wiki/Installation for more information.

**Comment by MindfulMe** [comment]
If you still have the problem even after the right installation of THEOS, then go to Xcode > Preferences > Locations > Command Line tools, and set something from drop-down menu (i.e. Xcode 8.2). Works for me

**Comment by TweakiOS** [comment]
yes, it solved the issue.

**Comment by arielariel1010** [comment]
same problem. Tried to do what you suggested but no success..
