### ISSUE TITLE
Making respring Sim

### ISSUE THREAD

**Issue by the-casle** [angelXwind/simject#37]
Appears to be an error when making the setup

`==> Cleaning…
==> Cleaning…`
`> Making all for tool respring_simulator…
==> Compiling respring_simulator.mm (i386)…
respring_simulator.mm:8:10: fatal error: 'array' file not found
#include <array>
         ^~~~~~~
1 error generated.
`

**Comment by ruler225** [comment]
Not sure if there's a solution to this but I am having this problem as well. If anyone has a solution, I would appreciate it

**Comment by FromDerik** [comment]
edit respring_simulator/Makefile and change it to this:

`TARGET = macosx:clang::10.9
ARCHS = x86_64
include $(THEOS)/makefiles/common.mk

TOOL_NAME = respring_simulator
respring_simulator_FILES = respring_simulator.mm
respring_simulator_CFLAGS = -Wno-deprecated-declarations -std=c++11

include $(THEOS_MAKE_PATH)/tool.mk

after-all::
	@echo "Copying binaries..."
	@mkdir -p ../bin
	@cp -v $(THEOS_OBJ_DIR)/respring_simulator ../bin/`

**Comment by o28c14** [comment]
@FromDerik's comment solves my problem

**Comment by PoomSmart** [comment]
The recent commits fix this issue.
