### ISSUE TITLE
Make setup problem with xcode 9.3

### ISSUE THREAD

**Issue by berkeelevent** [angelXwind/simject#38]
<img width="951" alt="ekran resmi 2018-05-08 15 40 05" src="https://user-images.githubusercontent.com/13659573/39757639-29221532-52d6-11e8-9518-f7f4a9887d66.png">

trying to fix this problem since yesterday

high sierra 10.13.4
using xcode 9.3 with commandline tools installed
brew, ldid, openssl etc. installed
( sdk & heades are installed in theos )

**Comment by BarryWhite007** [comment]
im also having the exact same issue.

**Comment by cwjoshuak** [comment]
Hi guys, try this out. This is what my makefile inside respring_simulator now contains. I'm running macOS 10.13.5 and Xcode 9.4. @BarryWhite007  @berkeelevent 

```
TARGET = macosx:clang::10.9
ARCHS = x86_64
include $(THEOS)/makefiles/common.mk

TOOL_NAME = respring_simulator
respring_simulator_FILES = respring_simulator.mm
respring_simulator_CFLAGS = -Wno-deprecated-declarations -std=c++11

include $(THEOS_MAKE_PATH)/tool.mk

after-all::
	@echo "Copying binaries..."
	@mkdir -p ../bin
	@cp -v $(THEOS_OBJ_DIR)/respring_simulator ../bin/

```
