### ISSUE TITLE
generator does not implement Method::initializers

### ISSUE THREAD

**Issue by johnrickman** [angelXwind/simject#4]
I'm getting this when running make setup..any idea what causes this? Thinking it can't find theos.

==> Cleaning…
> Making all for tweak simject…
==> Preprocessing simject.xm…
simject.xm: error: generator does not implement Method::initializers
make[3]: *** [/Users/john/simject/.theos/obj/iphone_simulator/x86_64/simject.xm.793f0766.o] Error 2
make[2]: *** [/Users/john/simject/.theos/obj/iphone_simulator/x86_64/simject.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [simject.all.tweak.variables] Error 2

**Comment by angelXwind** [comment]
You need to run `make update-theos` first. You're using an old Theos install where the "internal" generator was still broken.

**Comment by johnrickman** [comment]
Thanks that worked!
