### ISSUE TITLE
Issue setting up simject with 'make setup'

### ISSUE THREAD

**Issue by chrisink** [angelXwind/simject#41]
While building module 'Foundation' imported from /Users/Chris/theos/Prefix.pch:11:
While building module 'ObjectiveC' imported from /Users/Chris/theos/sdks/MacOSX10.13.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:9:
In file included from <module-includes>:2:
In file included from /Users/Chris/theos/sdks/MacOSX10.13.sdk/usr/include/objc/./Protocol.h:51:
/Users/Chris/theos/sdks/MacOSX10.13.sdk/usr/include/objc/Object.h:141:28: error: 
      expected a type
- (id)forward: (SEL)sel : (marg_list)args;
                           ^
/Users/Chris/theos/sdks/MacOSX10.13.sdk/usr/include/objc/Object.h:142:29: error: 
      expected a type
- (id)performv: (SEL)sel : (marg_list)args;
                            ^
While building module 'Foundation' imported from /Users/Chris/theos/Prefix.pch:11:
In file included from <module-includes>:2:
In file included from /Users/Chris/theos/sdks/MacOSX10.13.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:8:
/Users/Chris/theos/sdks/MacOSX10.13.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:9:10: fatal error: 
      could not build module 'ObjectiveC'
#include <objc/NSObjCRuntime.h>
 ~~~~~~~~^
In file included from <built-in>:1:
/Users/Chris/theos/Prefix.pch:11:11: fatal error: could not build module
      'Foundation'
                #import <Foundation/Foundation.h>
                 ~~~~~~~^
4 errors generated.
make[4]: *** [/Users/Chris/simject/respring_simulator/.theos/obj/macosx/debug/i386/respring_simulator.mm.ea9b506d.o] Error 1
make[3]: *** [/Users/Chris/simject/respring_simulator/.theos/obj/macosx/debug/i386/respring_simulator] Error 2
make[2]: *** [internal-tool-all_] Error 2
make[1]: *** [respring_simulator.all.tool.variables] Error 2
make: *** [all] Error 2

**Comment by afnanahmad** [comment]
@chrisink try this fix: https://github.com/angelXwind/simject/issues/37#issuecomment-400916548
it worked for me.
