### ISSUE TITLE
Another error signing simject during make setup

### ISSUE THREAD

**Issue by TnnsBeast** [angelXwind/simject#44]
here's what I keep getting

iPhone Developer: ambiguous (matches "iPhone Developer: #this is where my email is (68BJHHWDL9)" and "iPhone Developer: #this is where my second email is (6P645ATJN8)" in /Users/tnns_beast22/Library/Keychains/login.keychain-db)
make[3]: *** [/Users/tnns_beast22/simject/simject/.theos/obj/iphone_simulator/debug/simject.dylib] Error 1
rm /Users/tnns_beast22/simject/simject/.theos/obj/iphone_simulator/debug/simject.dylib.7876ddb4.unsigned
make[2]: *** [internal-library-all_] Error 2
make[1]: *** [simject.all.tweak.variables] Error 2
make: *** [all] Error 2

**Comment by PoomSmart** [comment]
Looks like you have redundant developer certificates of the same email. Open Keychain Access app and remove the older/unused one.

**Comment by snazzey** [comment]
THANK YOU SOOOO MUCH I HAVE TRIED LITERALLY EVERYTHING

**Comment by p-x9** [comment]
If multiple certificates exist, the following procedure could be used to specify the desired certificate

1. Create an identity for the desired certificate
See the following link
https://support.apple.com/lv-lv/guide/keychain-access/kyca6343b6c9/mac
1. Set TARGET_CODESIGN_FLAGS in Makefile
TARGET_CODESIGN_FLAGS = --sign "YOUR IDENTITY"
