### ISSUE TITLE
missing required architecture i386 in file

### ISSUE THREAD

**Issue by BandarHL** [angelXwind/simject#45]
![screen shot 2019-02-24 at 12 10 16 am](https://user-images.githubusercontent.com/31299470/53291719-d64f0300-37c8-11e9-82db-ae8cd1ed5e46.png)
![screen shot 2019-02-24 at 12 10 57 am](https://user-images.githubusercontent.com/31299470/53291721-d6e79980-37c8-11e9-924e-91599342e5d5.png)

**Comment by PoomSmart** [comment]
Do `ARCHS=x86_64` in the `respring_simulator`’s Makefile

**Comment by BandarHL** [comment]
thanks it's working now
![screen shot 2019-02-24 at 7 57 53 pm](https://user-images.githubusercontent.com/31299470/53302364-7e6ad780-386e-11e9-98d0-5091c334696a.png)

**Comment by jontelang** [comment]
Is there a reason it currently has `+ARCHS = ...` instead of just `ARCHS = ...`? At https://github.com/angelXwind/simject/blob/master/respring_simulator/Makefile#L2

(I just had the same issue and removing the + solved it for me)

**Comment by PoomSmart** [comment]
@jontelang That was a typo and surprisingly I hadn’t noticed that until now. This should be fixed as soon as possible.

**Comment by jontelang** [comment]
Oh okay, cool :+1:
