### ISSUE TITLE
Makefile:4: /makefiles/common.mk: No such file or directory Catalina

### ISSUE THREAD

**Issue by mac-user669** [angelXwind/simject#51]
When I try to install Simject on macOS Catalina, it says this:
```
Makefile:4: /makefiles/common.mk: No such file or directory
Makefile:10: /tool.mk: No such file or directory
make[1]: *** No rule to make target `/tool.mk'.  Stop.
make: *** [clean] Error 2
```
I'm not sure if this is a problem caused by running Xcode 10 instead of 11, but that wouldn't make very much sense. Thanks

**Comment by PoomSmart** [comment]
You need to define `$THEOS` variable.

https://github.com/theos/theos/wiki/Installation-macOS (Step 2)

**Comment by mac-user669** [comment]
I have tried. I uninstalled and reinstalled Theos even.

**Comment by PoomSmart** [comment]
What's the output of `echo $THEOS` from your Terminal?

**Comment by mac-user669** [comment]
$ echo $THEOS

$ 

I'm not sure why it's blank, I think Catalina broke something

**Comment by lucaIz-ldx** [comment]
Did you change default shell to zsh in Catalina? If true, try "echo "export THEOS=~/theos" >> ~/.zprofile"

**Comment by mac-user669** [comment]
@lucaIz-ldx it doesn't visually output anything. Is it supposed to?

**Comment by lucaIz-ldx** [comment]
@mac-user669 No. Restart terminal and run "echo $THEOS" should output "/Users/XXX/theos". I also got this problem after change default shell to zsh in Catalina.

**Comment by mac-user669** [comment]
Check the edit
