### ISSUE TITLE
Issue when running 'make setup'

### ISSUE THREAD

**Issue by JKakaofanatiker** [angelXwind/simject#57]
MacBook:simject jan$ make setup
Makefile:4: /makefiles/common.mk: No such file or directory
Makefile:10: /tool.mk: No such file or directory
make[1]: *** No rule to make target `/tool.mk'.  Stop.
make: *** [clean] Error 2

**Comment by PoomSmart** [comment]
Step 2: https://github.com/theos/theos/wiki/Installation-macOS

**Comment by arielariel1010** [comment]
did `echo "export THEOS=~/theos" >> ~/.zprofile` but still got this error..
