### ISSUE TITLE
Permission denied when trying compile any tweak.

### ISSUE THREAD

**Issue by arielariel1010** [angelXwind/simject#61]
i got this error:
`
hMBPslAriel2:simjectExampleTweak gavrielov$ make setup
==> Cleaning…
> Making all for tweak simjectExampleTweak…
==> Preprocessing simjectExampleTweak.xm…
==> Compiling simjectExampleTweak.xm (x86_64)…
==> Linking tweak simjectExampleTweak (x86_64)…
==> Generating debug symbols for simjectExampleTweak…
==> Stripping simjectExampleTweak (x86_64)…
rm /Users/gavrielov/simject/simjectExampleTweak/.theos/obj/iphone_simulator/x86_64/simjectExampleTweak.xm.mm
==> Preprocessing simjectExampleTweak.xm…
==> Compiling simjectExampleTweak.xm (i386)…
==> Linking tweak simjectExampleTweak (i386)…
==> Generating debug symbols for simjectExampleTweak…
==> Stripping simjectExampleTweak (i386)…
rm /Users/gavrielov/simject/simjectExampleTweak/.theos/obj/iphone_simulator/i386/simjectExampleTweak.xm.mm
==> Merging tweak simjectExampleTweak…
==> Signing simjectExampleTweak…
rm: /opt/simject/simjectExampleTweak.dylib: Permission denied
make: *** [setup] Error 1
`

and if i try with sudo:
`
hMBPslAriel2:simjectExampleTweak gavrielov$ sudo make setup
Makefile:10: /makefiles/common.mk: No such file or directory
Makefile:16: /tweak.mk: No such file or directory
make: *** No rule to make target /tweak.mk.  Stop.
`

any solves?

**Comment by arielariel1010** [comment]
@angelXwind @PoomSmart

**Comment by PoomSmart** [comment]
Declare THEOS variable property as per the documentation: https://github.com/theos/theos/wiki/Installation-macOS

**Comment by arielariel1010** [comment]
`hMBPslAriel2:grabbi2 gavrielov$ echo $theos
/Users/gavrielov/theos`
its declared..

**Comment by PoomSmart** [comment]
Isn’t it case-sensitive? Try declaring THEOS instead.
