### ISSUE TITLE
No devices booted

### ISSUE THREAD

**Issue by mickymouse1** [angelXwind/simject#8]
I'm having a problem - for some reason whenever I try loading up the simulator with the example provided I keep getting this output:

respring_simulator (C) 2016 Karen Tsai (angelXwind)
Injecting appropriate dynamic libraries from /opt/simject...
No devices are booted.
Respringing...
No devices are booted.

I have both the .dylib and .plist file in /opt/simject already...

I'm not sure what's wrong - can someone help?

**Comment by angelXwind** [comment]
You need to open the iOS Simulator first before executing `respring_simulator`.
