### ISSUE TITLE
simject not working on macOS Sierra

### ISSUE THREAD

**Issue by Hax0rDoge** [angelXwind/simject#9]
I went through the steps of setting up simject and also compiled and copied over the example tweak into the folder. However, when I load up the iOS 9.3 simulator the message doesn't appear. I tried making a new tweak with THEOS and it created it without any errors, so I'm pretty sure that THEOS is set up correctly.

Trying to run the respring_simject command gives me these errors
```
dyld: mach-o, but built for simulator (not macOS)
Abort trap: 6
```

I have tried to reinstall simject multiple times but it still doesn't work.

**Comment by angelXwind** [comment]
Huh, interesting. I assume you're using Xcode 8? I just tested simject with Xcode 8 (albeit on macOS 10.11.6) and it worked fine.

What we're seeing here might be due to a change Apple made in macOS 10.12.

**Comment by Hax0rDoge** [comment]
Yup I'm using Xcode 8 and I'm on macOS 10.12. 

Would it be better if I downgrade back to macOS 10.12 for now?

**Comment by angelXwind** [comment]
@Hax0rDoge Try `git pull`-ing to the latest commit (`509090e84abd3ba86fc23c5d3f3c8cd2b471dbbf` as of this writing) and try `make setup` again. Theoretically, I should have fixed it.

**Comment by Hax0rDoge** [comment]
Thank you!
<img width="308" alt="screen shot 2016-10-13 at 3 52 53 pm" src="https://cloud.githubusercontent.com/assets/20740005/19366545/240a9d08-915d-11e6-9057-e8476652bfae.png"/>
